-- GIVES THE CITY NAME WITH SHORTEST CITY NAME FROM STATION TABLE.
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY), CITY LIMIT 1;

-- GIVES THE CITY NAME WITH LONGEST CITY NAME FROM STATION TABLE.
SELECT CITY,LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1;

-- IF THERE ARE MORE THAN ONE CITY WITH SHORTEST AND LONGEST NAMES, THE ONE THAT COMES AT FIRST WHEN ORDERED ALPHABETICALLY IS SELECTED.